//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EADWebProj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Required(ErrorMessage = "This Id is required")]
        public string uid { get; set; }
        [StringLength(15, MinimumLength = 3, ErrorMessage = "The password  must atleast 3 character long")]
        public string password { get; set; }
        [StringLength(50,MinimumLength = 1, ErrorMessage = "The length of name must not be greater than 0")]
        public string name { get; set; }
        [StringLength(11, MinimumLength = 11, ErrorMessage = "The length of phone must be exactly 11 digit")]
        public string phone { get; set; }
    }
}
